#ifndef SCALA_LEXER_ACCESSFLAGS_H
#define SCALA_LEXER_ACCESSFLAGS_H

#include <cstdint>

/**
 * JVM Access Flags for classes, fields, and methods
 * Reference: https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html
 */
namespace AccessFlags {

    // ==================== Common Flags ====================
    constexpr uint16_t ACC_PUBLIC       = 0x0001;  // Declared public; may be accessed from outside its package
    constexpr uint16_t ACC_PRIVATE      = 0x0002;  // Declared private; accessible only within the defining class
    constexpr uint16_t ACC_PROTECTED    = 0x0004;  // Declared protected; may be accessed within subclasses
    constexpr uint16_t ACC_STATIC       = 0x0008;  // Declared static
    constexpr uint16_t ACC_FINAL        = 0x0010;  // Declared final; no subclasses/overrides allowed

    // ==================== Class-specific Flags ====================
    constexpr uint16_t ACC_SUPER        = 0x0020;  // Treat superclass methods specially when invoked by invokespecial
    constexpr uint16_t ACC_INTERFACE    = 0x0200;  // Is an interface, not a class
    constexpr uint16_t ACC_ABSTRACT     = 0x0400;  // Declared abstract; must not be instantiated
    constexpr uint16_t ACC_SYNTHETIC    = 0x1000;  // Declared synthetic; not present in the source code
    constexpr uint16_t ACC_ANNOTATION   = 0x2000;  // Declared as an annotation type
    constexpr uint16_t ACC_ENUM         = 0x4000;  // Declared as an enum type

    // ==================== Field-specific Flags ====================
    constexpr uint16_t ACC_VOLATILE     = 0x0040;  // Declared volatile; cannot be cached
    constexpr uint16_t ACC_TRANSIENT    = 0x0080;  // Declared transient; not written or read by a persistent object manager

    // ==================== Method-specific Flags ====================
    constexpr uint16_t ACC_SYNCHRONIZED = 0x0020;  // Declared synchronized; invocation is wrapped by a monitor use
    constexpr uint16_t ACC_BRIDGE       = 0x0040;  // A bridge method, generated by the compiler
    constexpr uint16_t ACC_VARARGS      = 0x0080;  // Declared with variable number of arguments
    constexpr uint16_t ACC_NATIVE       = 0x0100;  // Declared native; implemented in a language other than Java
    constexpr uint16_t ACC_STRICT       = 0x0800;  // Declared strictfp; floating-point mode is FP-strict

    /**
     * Convert Scala modifiers to JVM access flags for classes
     */
    inline uint16_t classFlags(bool isPublic, bool isFinal, bool isAbstract) {
        uint16_t flags = ACC_SUPER;  // Always set for classes (not interfaces)
        if (isPublic) flags |= ACC_PUBLIC;
        if (isFinal) flags |= ACC_FINAL;
        if (isAbstract) flags |= ACC_ABSTRACT;
        return flags;
    }

    /**
     * Convert Scala modifiers to JVM access flags for fields
     */
    inline uint16_t fieldFlags(bool isPublic, bool isPrivate, bool isProtected, bool isFinal) {
        uint16_t flags = 0;
        if (isPublic) flags |= ACC_PUBLIC;
        else if (isPrivate) flags |= ACC_PRIVATE;
        else if (isProtected) flags |= ACC_PROTECTED;
        if (isFinal) flags |= ACC_FINAL;
        return flags;
    }

    /**
     * Convert Scala modifiers to JVM access flags for methods
     */
    inline uint16_t methodFlags(bool isPublic, bool isPrivate, bool isProtected, bool isFinal, bool isAbstract) {
        uint16_t flags = 0;
        if (isPublic) flags |= ACC_PUBLIC;
        else if (isPrivate) flags |= ACC_PRIVATE;
        else if (isProtected) flags |= ACC_PROTECTED;
        if (isFinal) flags |= ACC_FINAL;
        if (isAbstract) flags |= ACC_ABSTRACT;
        return flags;
    }

}  // namespace AccessFlags

#endif // SCALA_LEXER_ACCESSFLAGS_H
