#ifndef SCALA_LEXER_CLASSFILEWRITER_H
#define SCALA_LEXER_CLASSFILEWRITER_H

#include <cstdint>
#include <vector>
#include <string>
#include <fstream>

#include "AccessFlags.h"
#include "BytecodeBuffer.h"
#include "semantic/tables/tables.hpp"

class ConstantPoolBuilder;
class ClassMetaInfo;
class MethodMetaInfo;
class FieldMetaInfo;

/**
 * ClassFileWriter - generates JVM .class file from ClassMetaInfo
 *
 * .class file structure:
 * - Magic number (0xCAFEBABE)
 * - Version (52.0 for Java 8)
 * - Constant Pool
 * - Access flags
 * - This class index
 * - Super class index
 * - Interfaces (empty for our Scala subset)
 * - Fields
 * - Methods
 * - Attributes (SourceFile optional)
 */
class ClassFileWriter {
private:
    ClassMetaInfo* classInfo;
    ConstantPoolBuilder* constantPool;
    std::vector<uint8_t> bytes;

    // Constant pool indices for commonly used entries
    uint16_t thisClassIndex = 0;
    uint16_t superClassIndex = 0;
    uint16_t codeAttributeNameIndex = 0;

    // Helper to write big-endian values
    void writeU1(uint8_t value);
    void writeU2(uint16_t value);
    void writeU4(uint32_t value);
    void writeBytes(const std::vector<uint8_t>& data);

    // Structure writers
    void writeMagic();
    void writeVersion();
    void writeConstantPool();
    void writeAccessFlags();
    void writeThisClass();
    void writeSuperClass();
    void writeInterfaces();
    void writeFields();
    void writeMethods();
    void writeClassAttributes();

    // Field generation
    void writeField(FieldMetaInfo* field);
    uint16_t getFieldAccessFlags(FieldMetaInfo* field);

    // Method generation
    void writeMethod(MethodMetaInfo* method);
    void writeDefaultConstructor();
    uint16_t getMethodAccessFlags(MethodMetaInfo* method);
    std::vector<uint8_t> generateCodeAttribute(MethodMetaInfo* method);

    // Prepare constant pool with required entries
    void prepareConstantPool();

public:
    explicit ClassFileWriter(ClassMetaInfo* classInfo);

    /**
     * Generate complete .class file bytes
     */
    std::vector<uint8_t> generate();

    /**
     * Write .class file to disk
     */
    bool writeToFile(const std::string& path);

    /**
     * Get the generated bytes (call after generate())
     */
    const std::vector<uint8_t>& getBytes() const { return bytes; }
};

#endif // SCALA_LEXER_CLASSFILEWRITER_H
