#ifndef SCALA_COMPILER_SEMANTICERRORCODE_H
#define SCALA_COMPILER_SEMANTICERRORCODE_H


enum SemanticErrorCode {
    EMPTY_AST_TREE = 1000,

    VAR_REDEFINITION = 1001,
    VAL_REASSIGNMENT = 1002,
    VAR_INVALID_TYPE_CAST = 1003,
    FINAL_FIELD_OVERRIDE = 1004,
    ABSTRACT_FIELD_NOT_OVERRIDEN = 1005,
    VAR_NOT_INITIALIZED = 1006,
    UNDEFINED_VAR = 1007,
    FIELD_REDEFINITION = 1008,

    TYPE_OVERFLOW = 1009,
    DIVIDE_BY_ZERO = 1010,
    TYPE_MISMATCH = 1011,
    NULL_POINTER_ACCESS = 1012,
    INVALID_COMBINATION_OF_MODIFIERS = 1013,
    UNDECLARED_TYPE = 1014,

    INVALID_ARRAY_ASSIGNMENT = 1015,
    INVALID_DIMENSION_SIZE = 1016,
    INDEX_OUT_OF_ARRAY_BOUNDS = 1017,
    HETEROGENEOUS_ARRAY_TYPES = 1018,
    FOR_LOOP_NOT_ARRAY = 1019,
    EXPR_NOT_ARRAY = 1020,
    IF_BRANCHES_RETURNS_DIFFERENT_TYPES = 1021,

    INVALID_INHERITANCE = 1022,
    FINAL_CLASS_INHERITANCE = 1023,
    UNDEFINED_CLASS = 1024,
    CLASS_REDEFINITION = 1025,
    CONSTRUCTOR_ALREADY_EXISTS = 1026,
    CONSTRUCTOR_NOT_FOUND = 1027,
    CONSTRUCTOR_CONTAINS_INCORRECT_INSTRUCTION = 1049,
    CLASS_NOT_FOUND = 1028,
    ABSTRACT_CLASS_INSTANTIATED = 1029,
    CLASS_CAN_NOT_BE_OVERRIDE = 1030,
    MAIN_CLASS_NOT_DEFINED = 1031,

    FINAL_METHOD_OVERRIDE = 1032,
    METHOD_ALREADY_EXISTS = 1033,
    MISSING_RETURN_VALUE = 1034,
    RETURN_FROM_VOID = 1035,
    RETURN_TYPE_MISMATCH = 1036,
    UNEXPECTED_RETURN = 1037,
    CONDITION_NOT_BOOLEAN = 1038,
    METHOD_NOT_FOUND = 1039, // Метод с именем не найден
    METHOD_CANDIDATE_NOT_FOUND = 1040, // Метода с именем и аргументами определенных типов не найден
    INVALID_OPERATOR = 1041, // оператор применён к несовместимым типам
    NULL_SEMANTIC_TYPE_FOR_LEFT_EXPR = 1042,
    NULL_SEMANTIC_TYPE = 1043,
    SAME_ARGUMENTS_NAMES = 1044,
    MAIN_METHOD_NOT_DEFINED = 1045,
    ABSTRACT_METHOD_NOT_IMPLEMENTED = 1046,
    INTERNAL_ERROR = 1047,
    INCOMPATIBLE_ARRAY_ELEMENT_TYPES = 1048,
};


#endif // SCALA_COMPILER_SEMANTICERRORCODE_H